name: Andoird Build

on: 
  push:
      branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code  
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Set Up JDK
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 1.8

      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x AplicacionMovil/gradlew
      
      - name: Run-Lint
        run: ./gradlew lintDebug
        working-directory: ./AplicacionMovil
        
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint_html_report
          path: AplicacionMovil/app/build/reports/lint-results-debug.html
          
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x AplicacionMovil/gradlew

      - name: Run tests
        run: ./gradlew test
        working-directory: ./AplicacionMovil

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: AplicacionMovil/app/build/reports/tests/testDebugUnitTest/
          
  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x AplicacionMovil/gradlew

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck          
          working-directory: ./AplicacionMovil

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: AplicacionMovil/app/build/reports/androidTests/connected/
      
      #- name: Run Tests
        #run: ./gradlew test
        #working-directory: ./AplicacionMovil
        
      #- name: Build Project
        #run: ./gradlew assembl
        #working-directory: ./AplicacionMovil
        
  package:
    needs: [instrumentation-test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x AplicacionMovil/gradlew

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: ./gradlew assembleDebug          
        working-directory: ./AplicacionMovil

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: expense-manager.apk
          path: AplicacionMovil/app/build/outputs/apk/debug/app-debug.apk
