# This is a basic workflow to help you get started with Actions

name: Andoird Build

# Controls when the action will run. 
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: Make gradlew executable
        run: chmod +x Practica1/gradlew
      
      - name: Run-Lint
        run: ./gradlew test
        working-directory: ./Practica1
        
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint_html_report
          path: app/build/reports/lint-results-debug.html
      
      #- name: Run Tests
        #run: ./gradlew test
        #working-directory: ./Practica1
        
      #- name: Build Project
        #run: ./gradlew assembl
        #working-directory: ./Practica1
